name: branch

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Setup helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup jsonnet
        run: |
          export GO111MODULE=on
          export GOPATH="${HOME}/go"
          export PATH="${GOPATH}/bin:${PATH}"
          make build-deps

      - name: Build
        run: |
          export GOPATH="${HOME}/go"
          export PATH="${GOPATH}/bin:${PATH}"
          make all

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: false
          keep_files: true
